name: build_tox_tests

on: [push]
jobs:
  build_tox_tests_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tox in docker
        run: docker compose up --build
