name: build_tox_tests

on: [push]
jobs:
  build_tox_tests_docker:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --tag hls-metadata

      - name: Tox tests in container
        run: docker run hls-metadata
